name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2
  EB_APPLICATION_NAME: fridge-rescue-server-app
  EB_ENVIRONMENT_NAME: fridge-rescue-server-app-env

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: develop

    steps:
      # 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # JDK 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Gradle build (Test 제외)
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x test

      - name: Get current time
        uses: josStorer/get-current-time@v2.1.1
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      # JAR(application.jar) to ZIP for Beanstalk
      # ZIP File encludes Procfile, .ebextensions, .playform
      - name: Generate Deployment Package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r deploy.zip .

      # Beanstalk Deploy
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_EB_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_EB_SECRET_KEY }}
          application_name: ${{ env.EB_APPLICATION_NAME }} # EB Application Name
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }} # EB Environment Name
          version_label: version-${{ steps.current-time.outputs.formattedTime }} # 배포 버전은 타임스탬프를 이용하여 구분
          region: ${{ env.AWS_REGION }}
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 300
